### ISSUE TITLE
Replace Haml with Slim

### ISSUE THREAD

**Issue by dgdavid** [proiectus/yet-another-personal-diary#24]
According with the README

> to play with different frameworks or tools used in every day work.

maybe we can use [`slim-rails`](https://github.com/slim-template/slim-rails) instead of [`haml-rails`](https://github.com/indirect/haml-rails).

Besides to use a different template system, it seems that the performance could be better, such as [`hamilt`](https://github.com/k0kubun/hamlit)'s<sup>1</sup> [`benchmark`](https://github.com/k0kubun/hamlit#what-is-hamlit) shows.

--

<sup>1</sup> `High Performance Haml Implementation`

**Comment by DavidKang** [comment]
Yes, I also think that we can try `slim-rails` to see the performance of `slim`
